import React from 'react'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>FEUP JS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://www.feup.cn">FEUP JS</a>
        </h1>

        <h1 className={styles.title}>
         
        </h1>

        <h1 className={styles.title}>
          Welcome to <a href="https://mock.feup.cn">mock 数据</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>前端生态</code>
          Welcome to <a href="https://mock.feup.cn">mock 数据</a>
          
          {' '}
          Welcome to <a href="https://github.com/feupjs">github FEUP JS</a>
        </p>
      <a href="https://beian.miit.gov.cn"> 冀ICP备12011960号</a>
      </main>
    </div>
  )
}
